services:
  busy:
    build: .
    image: nalanj/busy:latest
    container_name: busy
    environment:
      - MINIMAX_API_KEY
    volumes:
      - ./config/example.yaml:/config/example.yaml:ro
      - ./state:/root/.local/share/busy
    network_mode: host
    command: ["--config", "/config/example.yaml"]
    stdin_open: true
    tty: true
