[tools]
go = "latest"

[tasks.build]
run = "go build -o dist/busy ./cmd/busy/"

[tasks.docker-build]
run = "go build -o dist/busy ./cmd/busy/ && docker build -t nalanj/busy ."

[tasks.docker-clean]
run = "docker image prune -f"

[tasks.test]
run = "go test ./..."

[tasks.all]
run = ["build", "test"]
